import pandas as pd
df = pd.read_csv('data/sentiment_processed_data.csv')
print(f"成功读取数据，共 {len(df)} 行")
df_dedup = df.drop_duplicates(subset=['cleaned_text'], keep='first')
print(f"去重后数据行数: {len(df_dedup)}")
print(f"移除重复评论数: {len(df) - len(df_dedup)} 条")
df_dedup.to_csv('./data/final_data_of_train.csv', index=False, encoding='utf-8')
print("\n" + "=" * 50)
print("数据处理完成!")
print(f"原始数据: {len(df):,} 行")
print(f"处理后数据: {len(df_dedup):,} 行")
print(f"数据减少: {len(df) - len(df_dedup):,} 行")
print(f"保留率: {(len(df_dedup) / len(df)) * 100:.1f}%")